sudo: false
notifications:
  email: false
language: node_js
python:
- '2.7'
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  matrix:
  - RUN_TEST=test
  - RUN_TEST=test-sherlocked
  global:
  - secure: F4pIfZ2papA6JrGwOy6nA0QIvxLpwPDIcC2xl7oUXSseGiDTIHN+CqU0deajIMYAxWevAehLjTsFQk9kWZ9DSC/M9HC0I1+CsIhSktE/PkGZ/H7cNPifHFxnc97y7gMfwWUtcPKpslF4Ub41jiGgqryPFfQt83/VfJQqWidZnemWq7LrEnJPRyziBjB0K3ZuLIVmolrOnMO4hUQOUegCDpU54mQfbMBDzDQMFE82W4RAJu9GfuoRgN1xzaYaHJJiX9sarXO4UuT5VIqN0mWh3XbcGyG7u4FmRaMgeshH4bd3QHxCKWw2pVVwBkV1/3wplPBP7Snp/ew2NFnhcAKhSx/U34Xiw3ydsAqc616lnyvLnQko03XFaA+VTLA7mLLLtiU2UMbDjyfFRT98E++P2gA/GTLPZrVvucy/0ORQFBrAr1Khje3o9JTpg9MqIaZKkfbVsvCe350414+WlIgwxCt/3Q7G0U0ooWlsGR9ckr5o/O73jBocOlF+t7JWTQqES+RoKfRLjioE/0TYQzBntVHHYJ9VTmGK4pa+TESDJzYy0PU0WFfYFlZwJ1s+5Rvd4oyOEYvFU/Qa3CBd0pO/qhTBcz0+P/av3S0gFwoFBnP38REnOsoKMhPFJLyPOoCDnOs8PU8AuCJ8vrKUVYbvh13bR/xjnDZqMMe8qTvSTrk=
  - secure: vxxT1d35zCVgRnFKzita5DVwvWxXaPR+fHOlo72iH0GvRdW80gT0wWzi3zW09kGHtnh+CK1ENXyTw1yXWob/Sp4LgE6dEbA0RJYPD1wrgbZe25G9dRw/M4I7SRZrnLogGuRj8LEyreVwVSUIKQReSfb1jOSLY2n0l8KIwekOmzBwJsrE7cjgOTbGPvhYOcVp846gKx8aHFcBs3fSBZfqSEAcZqFj33ywph/z94kFNrtHapJlFAjOiKY3VjH1NVB7eMMTUPZl27M69T6ZGglmE6uTijL8zI6L7Nv26+bdYglixQi7Y304OV0Mb2mDFiZRqVFTqmJw+v7i7eOaoeLce9FGOHNGEyr874nJ6AHU95o4niHJ/XzBW1PlAPj2qxkTd02GpEvWQOStB9KULwzjbW+al4LNdOYTi0nRdTe7/V5UtTic7cPnXQvT64+VxNO8t8PB5YF4+hWTMJeU9fcl7zeRKVBPxqvRbWghTxrgH5hGMlzdsFq7Nrc2awqshqV/BMn4C+f/HWMnESp0ip//fiKSaWWJawi50j4EGX5cUo33ZKrdinw7dZCQ3vUKjqCJbrSodXodhTSoZh/bqfgiq38QRTvdZ+hwIRHGBExRLs7xFDrd3ZD2XuQTXOxM9gSTJc2cami641YwAvTNgjhMyNJPYbqUmk34CGtAj3gaQIM=
script:
- make $RUN_TEST
cache:
  directories:
  - node_modules
